services:
    frontend:
        build:
            context: .
            dockerfile: .config/Dockerfile
        image: repomanager-1.0.0
        container_name: repomanager-frontend
        entrypoint: sh -c
        command: /app/.config/entrypoint/manager.sh
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/api/check"]
            interval: 1s
            retries: 360

    worker:
        image: repomanager-1.0.0
        container_name: repomanager-worker
        entrypoint: sh -c
        command: /app/.config/entrypoint/worker.sh
        depends_on:
            frontend:
                condition: service_healthy