services:
    frontend:
        build:
            dockerfile: .config/Dockerfile.dev
        image: repomanager-dev-1.0.0
        command: /app/.config/manager-dev.sh
        expose:
            - 8080
            - 5555
        ports:
            - "8080:8080"
            - "5555:5555"
        volumes:
            - ./:/app/
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/check"]
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DATABASE_URL=mysql://root:localhost@repomanager-db:3306/repomanager

    worker:
        image: repomanager-dev-1.0.0
        volumes:
            - ./:/app/
        environment:
            - DATABASE_URL=mysql://root:localhost@repomanager-db:3306/repomanager

    repomanager-db:
        ports:
            - '3306:3306'
        volumes:
            - ./db/mysql:/var/lib/mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=repomanager
            - MYSQL_ROOT_PASSWORD=localhost